Azure Policy extension and assign an Azure Policy for Azure Arc-enabled Kubernetes
microsoft/azure_arc pull request #1258
Opened 2022-06-21 09:12 UTC by lanicolas

New scenario to integrate Azure Arc-enabled Kubernetes with Azure Policy extension and assign an Azure Policy to the Azure Arc-enabled Kubernetes cluster resource group. By Pablo Ameijeiras

2022-06-22 08:11 UTC, sebassem reviewed
Minor lingo comments
change resource group name to Arc-K8s-Demo to be aligned with other scenarios?

2022-06-22 08:11 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_k8s/day2/multi_distributions/azure_policy/_index.md
> +  - Login to your Azure subscription using the SPN credentials
```suggestion
  - Login to your Azure subscription using the service principal credentials
```

2022-06-22 08:11 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_k8s/day2/multi_distributions/azure_policy/_index.md
> +  - Create Azure Policy cluster extension instance
```suggestion
  - Create the Azure Policy cluster extension instance
```

2022-06-22 08:11 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_k8s/day2/multi_distributions/azure_policy/_index.md
> +- If there were pods that exceeded the limit before applying the Azure Policy, they will not be removed, but we can see which ones do not comply in the Azure Policy service in the Compliance tab (sel
```suggestion
- If there were pods that exceeded the limit before applying the Azure Policy, they will not be removed, but we can see which ones do not comply in the Azure Policy service in the Compliance tab, select the non-compliance event
```

2022-06-22 08:11 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_k8s/day2/multi_distributions/azure_policy/_index.md
> +- This is the non-compliance pod:
```suggestion
- This is the non-compliant pod:
```

2022-06-22 08:26 UTC, sebassem commented on docs/azure_arc_jumpstart/azure_arc_k8s/day2/multi_distributions/azure_policy/_index.md
> +- The Azure Policy we have assigned works as a [LimitRange](https://kubernetes.io/docs/concepts/policy/limit-range/), but we do not specify any namespace, so the Azure Policy will be applied on all n
Better to show steps on how to apply this deployment to the cluster

2022-06-27 20:10 UTC, dkirby-ms requested changes

2022-06-27 20:10 UTC, merged