Minor changes to GKE/AKS helm-gitops
microsoft/azure_arc pull request #131
Opened 2020-10-04 21:44 UTC by NillsF

Based on the PR review for Kind Helm GitOps, making the changes from the PR review in the AKS/GKE gitops scenario.

2020-10-04 22:14 UTC, likamrat commented on azure_arc_k8s_jumpstart/aks/gitops/helm/az_k8sconfig_helm_cleanup.sh
> +# Logging in to Azure using service principal
```suggestion
# Log in to Azure using service principal
```

2020-10-05 04:39 UTC, likamrat commented on azure_arc_k8s_jumpstart/gke/gitops/helm/az_k8sconfig_helm_cleanup.sh
> +az login --service-principal --username $appId --password $password --tenant $tenantId
```suggestion
echo "Log in to Azure with Service Principle"
az login --service-principal --username $appId --password $password --tenant $tenantId
```

2020-10-05 04:40 UTC, likamrat commented on azure_arc_k8s_jumpstart/aks/gitops/helm/az_k8sconfig_helm_cleanup.sh
> +export appId='<Your Azure Service Principle name>'
```suggestion
export appId='<Your Azure Service Principal name>'
```

2020-10-05 04:44 UTC, likamrat commented on azure_arc_k8s_jumpstart/aks/gitops/helm/az_k8sconfig_helm_cleanup.sh
```suggestion
az aks get-credentials --name $arcClusterName --resource-group $resourceGroup --overwrite-existing

```

2020-10-05 04:47 UTC, likamrat requested changes
- looks like *az aks get-credentials* command was removed for the AKS script (?)
- Remove AKS reference from GKE

2020-10-06 18:49 UTC, NillsF commented
Accepted changes and changed principle --> principal in a couple more places.

2020-10-13 01:40 UTC, likamrat approved these changes

2020-10-13 01:40 UTC, merged