Set up a Video Indexer enabled by Arc environment.
microsoft/azure_arc pull request #2070
Opened 2023-08-21 14:25 UTC by shemers

**Is your feature request related to a new Jumpstart scenario you would like to contribute?**

Yes, a new scenario.

**Is your feature request related to a problem? Please describe.** No

**Describe the solution you'd like.**
How to set up a Video Indexer enabled by Arc environment.

**Describe alternatives you've considered.**
N\A

**Additional context.**
N\A

2023-08-29 22:05 UTC, dkirby-ms requested changes
Thanks for your PR.

Several things to look at:

* See my comments about styling for NOTE and use of "TIP". 
* Need to show screenshots to help user visualize what to expect
* Need to add a section at the end that points to how to clean up the environment. You can do this by linking to one of the existing K8s scenarios cleanup section, or you can do it by explaining to user to delete the RG used if using AKS. 
* For the section where user has to configure some parameters to pass to the extension, be very explicit and show a working command with the exact command to run. You can see examples of this in other scenarios or in ArcBox docs.
* Consider making the scenario anchored around a specific K8s basic scenario rather than giving user option of using AKS or bring their own K8s. I think it will be clearer if the user is following one guide to setup a base K8s distro, and then they use this guide which refers back to the guide they just followed.

2023-08-29 22:05 UTC, dkirby-ms commented on docs/azure_arc_jumpstart/azure_arc_video_indexer/aks/azure_arc_video_indexer_az/_index.md
> +
show screenshot showing success

2023-08-29 22:05 UTC, dkirby-ms commented on docs/azure_arc_jumpstart/azure_arc_video_indexer/aks/azure_arc_video_indexer_az/_index.md
> +
show screenshot with success. Also be sure to show an example that uses every parameter in an example basic configuration. Dont assume user will know which values to use for any parameter and explicitly show what will work with the recommended setup presented in the guide.

2023-08-29 22:05 UTC, dkirby-ms commented on docs/azure_arc_jumpstart/azure_arc_video_indexer/aks/azure_arc_video_indexer_az/_index.md
> +
show screenshot with successful kubectl output

2023-08-29 22:05 UTC, dkirby-ms commented on docs/azure_arc_jumpstart/azure_arc_video_indexer/aks/azure_arc_video_indexer_az/_index.md
> +> **NOTE:** You must specify the cluster name and resurce group name in order to update the extension.
NOTE styling

2023-08-29 22:05 UTC, dkirby-ms commented on docs/azure_arc_jumpstart/azure_arc_video_indexer/aks/azure_arc_video_indexer_az/_index.md
> +
show screenshot with successful output

2023-10-04 13:27 UTC, likamrat commented
Closing this for now as @dkirby-ms working on a new VI scenario

2023-10-04 13:27 UTC, closed without merging