Product rebranding rebranding: Microsoft Defender for Cloud and Microsoft Container Registry
microsoft/azure_arc pull request #927
Opened 2022-01-11 14:54 UTC by lanicolas

Rename Azure Security Center for Microsoft Defender and Microsoft Container Registry on all scenarios where it is referenced.

2022-01-18 16:06 UTC, lanicolas commented
All images are now updated to reflect Defender instead of ASC

2022-01-23 15:40 UTC, likamrat commented on azure_arc_k8s_jumpstart/cluster_api/capi_defender_extension/azure_defender_k8s_extension.sh
> +export k8sExtensionName='<Azure Defender Extension Name>' #default: 'microsoft.azuredefender.kubernetes'
```suggestion
export k8sExtensionName='<Microsoft Defender for Cloud extension name>' #default: 'microsoft.azuredefender.kubernetes'
```

2022-01-23 15:57 UTC, likamrat commented on docs/azure_arc_jumpstart/azure_arc_k8s/day2/cluster_api/cluster_api_defender_extension/_index.md
> +The following README will guide you on how to enable [Microsoft Defender for Cloud](https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-containers-introduction?tabs=defender-for-co
```suggestion
The following README will guide you on how to enable [Microsoft Defender for Cloud](https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-containers-introduction?tabs=defender-for-container-arch-aks) for a Cluster API that is projected as an Azure Arc-connected cluster.
```

2022-01-23 15:59 UTC, likamrat commented on docs/azure_arc_jumpstart/azure_arc_k8s/day2/cluster_api/cluster_api_defender_extension/_index.md
> +## Create Defender extensions instance
```suggestion
## Create Microsoft Defender for Containers extensions instance
```

2022-01-23 15:59 UTC, likamrat commented on docs/azure_arc_jumpstart/azure_arc_k8s/day2/cluster_api/cluster_api_defender_extension/_index.md
> +To create a new extension Instance, we will use the _k8s-extension create_ command while passing in values for the mandatory parameters. This scenario provides you with the automation to deploy the M
```suggestion
To create a new extension Instance, we will use the _k8s-extension create_ command while passing in values for the mandatory parameters. This scenario provides you with the automation to deploy the Microsoft Defender for Containers extension on your Azure Arc-enabled Kubernetes cluster.
```

2022-01-23 16:01 UTC, likamrat commented on docs/azure_arc_jumpstart/azure_arc_k8s/day2/cluster_api/cluster_api_defender_extension/_index.md
> +* Before integrating the cluster with Microsoft Defender for Cloud, click on the "Security (preview)" blade for the connected Arc cluster to show how the cluster is not currently being assessed by Mi
```suggestion
* Before integrating the cluster with Microsoft Defender for Cloud, click on the "Security (preview)" blade for the connected Azure Arc cluster to show how the cluster is not currently being assessed by Microsoft Defender for Cloud.
```

2022-01-23 16:02 UTC, likamrat commented on docs/azure_arc_jumpstart/azure_arc_k8s/day2/cluster_api/cluster_api_defender_extension/_index.md
> +* Also verify under the Extensions section of the Azure Arc-enabled Kubernetes cluster that the Defender extension is correctly installed.
```suggestion
* Also verify under the Extensions section of the Azure Arc-enabled Kubernetes cluster that the Microsoft Defender extension is correctly installed.
```

2022-01-23 16:07 UTC, likamrat requested changes
Minor updates

2022-01-24 08:43 UTC, lanicolas commented
changed

2022-01-26 15:05 UTC, likamrat approved these changes
LGTM

2022-01-26 15:05 UTC, merged